In [48]:
#question 1

import numpy as np

#(A)
arr = np.array([1,2,3,4,5,6])
rev = arr[::-1]
print(rev)

#(b)
array1 = np.array([[1,2,3], [2,4,5], [1,2,3]])

print(array1.flatten())
print(array1.ravel())

#(C)
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1 > arr2)

#(d)
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 


unique_x, counts_x = np.unique(x, return_counts=True)
mode_x = unique_x[np.argmax(counts_x)]
indices_x = np.where(x == mode_x)[0]
print(f"For array x: The most frequent value is {mode_x}, found at indices {indices_x}")

unique_y, counts_y = np.unique(y, return_counts=True)
mode_y = unique_y[np.argmax(counts_y)]
indices_y = np.where(y == mode_y)[0]
print(f"For array y: The most frequent value is {mode_y}, found at indices {indices_y}")


#(E)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())
print(sum(gfg))
print(gfg.sum(axis = 1))

#(F)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("Diagonal sum:", np.trace(n_array))
print("Eigen values: ", np.linalg.eigvals(n_array) )
print("Eigen vectors: ", np.linalg.eig(n_array) )
print("Inverse matrix: ", np.linalg.inv(n_array) )
print("Determinant: ", np.linalg.det(n_array) )

#(G)
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]] 

multiplication_1 = np.array(p) @ np.array(q)
print(f"Matrix multiplication (p1 @ q1):\n{multiplication_1}")
print("Covariance: ", np.cov(np.array(p), np.array(q)))

p1 = np.array([[1, 2], [2, 3], [4, 5]])
q1 = np.array([[4, 5, 1], [6, 7, 2]])

print(f"Matrix multiplication (p1 @ q1):", p1 @ q1)
# print("Covariance: ", np.cov(p1, q1)) ##GETTING PROBLEMS HERE


#(H)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Inner product: ", np.inner(x,y))
print("Outer product: ", np.outer(x,y))
print("Cartesian product: ", np.array(np.meshgrid(x.ravel(), y.ravel())).T.reshape(-1,2))




[6 5 4 3 2 1]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]
[[False False]
 [False False]]
For array x: The most frequent value is 1, found at indices [0 5 7 8 9]
For array y: The most frequent value is 1, found at indices [0 1 2]
45
[[20  9 16]]
[[14]
 [16]
 [15]]
Diagonal sum: 176
Eigen values:  [98.16835147 28.097044   49.73460452]
Eigen vectors:  EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
Inverse matrix:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant:  137180.0000000001
Matrix multiplication (p1 @ q1):
[[16 19]
 [26 31]]
Covariance:  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
Matrix multiplication (p1 @ q1): [[16 19  5]
 [26 31  8]
 [46 55 14]]
Inner product:  [[17 52]
 [13 62]]
Outer prod

In [60]:
## Question 2

#(A)
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(np.abs(array))
print("Percentiles for flattened arrays: ", np.percentile(array.flatten(), [25,50,75]))
print("Percentiles for column arrays: ", np.percentile(array, [25,50,75], axis = 0))
print("Percentiles for row arrays: ", np.percentile(array, [25,50,75], axis = 1))

print("Mean of flattened : ", np.mean(array.flatten(), axis = 0), "Median of flattened: ", np.median(array.flatten(), axis= 0), "Standard deviation of flattened: ", np.std(array.flatten(), axis = 0))
print("Mean of each column: ", np.mean(array, axis = 0), "Median of each column: ", np.median(array, axis= 0), "Standard deviation of each column: ", np.std(array, axis = 0))
print("Mean of each row: ", np.mean(array, axis = 1), "Median of each row: ", np.median(array, axis= 1), "Standard deviation of each row: ", np.std(array, axis =1))

#(b)
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.round(a))



[[1 2 3]
 [4 5 6]]
Percentiles for flattened arrays:  [-3.5 -0.5  2.5]
Percentiles for column arrays:  [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for row arrays:  [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean of flattened :  -0.5 Median of flattened:  -0.5 Standard deviation of flattened:  3.8622100754188224
Mean of each column:  [-1.5  1.5 -1.5] Median of each column:  [-1.5  1.5 -1.5] Standard deviation of each column:  [2.5 3.5 4.5]
Mean of each row:  [ 0.66666667 -1.66666667] Median of each row:  [ 1. -4.] Standard deviation of each row:  [2.05480467 4.78423336]
[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [71]:
#Question 3

#(a)
array = np.array([10, 52, 62, 16, 16, 54, 453])

print(array)
print("Sorted array: ", np.sort(array))
print("Indices sorted array: ", np.argsort(array))
print(np.sort(array)[0:4])
print(np.sort(array)[2:])

#(B)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integer elements", array[array == array.astype(int)])
print("Float elements", array[array != array.astype(int)])


[ 10  52  62  16  16  54 453]
Sorted array:  [ 10  16  16  52  54  62 453]
Indices sorted array:  [0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]
Integer elements [1. 2. 3. 2.]
Float elements [1.2 2.2]


In [ ]:
#Question 4
from PIL import Image as pillow

count = 0

def img_to_array(path):

    img = pillow.open(path)
    img_array = np.array(img)
    count = count + 1

    if img.mode == "L":
        print("Image in Grayscale")
        np.savetxt('grayscale_image_{count}.txt', img_array, fmt='%d')

    elif img.mode == "RGB":
        print("Image in RGB mode")
        reshaped_array = img_array.reshape(-1, 3)
        np.savetxt("RGB_image_{count}.txt", reshaped_array, fmt='%d')


def load_imagearray(path):
    image_array = np.loadtxt(path)
    print(image_array)

In [78]:
img_to_array("me.jpg")

Image in RGB mode
